# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c55805342c6311502c690c014454e816c22d8114dfe216526515d218193df3f1a3b198f0fca583625c79ad112bee9c485ab1cc55a15e3f735fa850aca01681

test:
  secret_key_base: 33782cf600ed797f96fdf075fb48eb4886bc4f68503144cba41e755823d855a130ef53ea85153031885116b3b3ce2fb42c65fcdf7caa072ee2d62506cc45d0e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
